### PR TITLE
Remove soft link and -data directory for new storage class

### PR DESCRIPTION
**Pull request by madhuthorat**
## Pull request checklist

```release-notes

```

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature Enhancement
- [ ] Test Automation 
- [ ] Code Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Community Operator listing 
- [ ] Other (please describe): 

## What is the current behavior?
- Soft links created to primary FS. Directory "pvc-xxx-data" created for each pv

## What is the new behavior?
-NO soft links created to primary FS. Remove creation of directory "pvc-xxx-data" created for each pv

## How risky is this change?
- [ ] Small, isolated change
- [x] Medium, requires regression testing
- [ ] Large, requires functional and regression testing

### CODE REVIEW

**Review by Jainbrt — COMMENTED** [review]
does this remove the dependecy for primaryFset going forward with new PVCs?

**Comment by madhuthorat** [comment]
> does this remove the dependecy for primaryFset going forward with new PVCs?

Yes, that is the intention. But at many places code won't go away for old PVCs. @deeghuge the change is done for both new and old storage class. I recall you wanted to check if we should do it for old storage class or not ?

**Review by amdabhad — APPROVED** [review]
LGTM

**Review by deeghuge — APPROVED** [review]
lgtm

**Comment by deeghuge** [comment]
> > does this remove the dependecy for primaryFset going forward with new PVCs?
> 
> Yes, that is the intention. But at many places code won't go away for old PVCs. @deeghuge the change is done for both new and old storage class. I recall you wanted to check if we should do it for old storage class or not ?

We should not do the changes for old storageClass.

**Pull request merged**
