### PR TITLE
removal of deprecated registrykey dependencies

### PR DESCRIPTION
**Pull request by badri-pathak**
## Pull request checklist

This is going to handle the issue [CSI - Remove the deprecated ibm-spectrum-scale-registrykey from CSI](https://github.ibm.com/IBMSpectrumScale/scale-core/issues/7909)

```release-notes

```

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature Enhancement
- [ ] Test Automation 
- [ ] Code Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Community Operator listing 
- [ ] Other (please describe): 

## What is the current behavior?

- Currently both the secret keys are being used based the registry key configuration.

## What is the new behavior?

- Going forward only the "ibm-entitlement-key" secret is the unified default key for image registry authentication. 

## How risky is this change?
- [ ] Small, isolated change
- [x] Medium, requires regression testing
- [ ] Large, requires functional and regression testing

### CODE REVIEW

**Comment by badri-pathak** [comment]
Operator Image: quay.io/badri_pathak/ibm-spectrum-scale-csi-operator:deprecatedRegistryKey_v3

**Comment by badri-pathak** [comment]
In the case of upgrade, SA is not getting updated with latest changes. Still in progress.

**Comment by badri-pathak** [comment]
Handled scenario of upgrade when SA changes not reflecting on the deployment and Daemonset.

Operator Image: quay.io/badri_pathak/ibm-spectrum-scale-csi-operator:deprecatedRegistryKey_v12

**Comment by badri-pathak** [comment]
Operator Image: quay.io/badri_pathak/ibm-spectrum-scale-csi-operator:deprecatedRegistryKey_v14

**Review by saurabhwani5 — COMMENTED** [review]
@hemalathagajendran can you please help in reviewing this pr ?

**Comment by saurabhwani5** [comment]
@hemalathagajendran do we need to make any changes regarding this PR in cnsa repo ?

**Review by hemalathagajendran — APPROVED** [review]

**Comment by hemalathagajendran** [comment]
> @hemalathagajendran do we need to make any changes regarding this PR in cnsa repo ?

We have to inform CNSA team so that they would generate install.yaml with these updated changes in case if they miss to generate

**Pull request merged**
