### PR TITLE
find out csi version and images (#425)

### PR DESCRIPTION
**Pull request by kulkarnicr**
enhance log collection script to collect csi version and pod image versions

### CODE REVIEW

**Comment by kulkarnicr** [comment]
fix includes following:

1. if user runs script with -v option (./spectrum-scale-driver-snap.sh -v); then versions and images are printed on stdout

2. if user runs script default way (./spectrum-scale-driver-snap.sh); then along with other logs; an extra file is created (ibm-spectrum-scale-csi-versions) that contains version details. In short, stdout output from 1. above is dumped into a file stored in output-directory/.

- command execution and output for 1. 
```
[root@spectral1 2021_07_10-08:00:22 ganesha425]$ git clone -b 425 https://github.com/kulkarnicr/ibm-spectrum-scale-csi.git
Cloning into 'ibm-spectrum-scale-csi'...
remote: Enumerating objects: 9586, done.
remote: Counting objects: 100% (381/381), done.
remote: Compressing objects: 100% (178/178), done.
remote: Total 9586 (delta 202), reused 332 (delta 182), pack-reused 9205
Receiving objects: 100% (9586/9586), 39.51 MiB | 16.98 MiB/s, done.
Resolving deltas: 100% (5533/5533), done.
[root@spectral1 2021_07_10-08:01:28 ganesha425]$ cd ibm-spectrum-scale-csi/tools/
[root@spectral1 2021_07_10-08:01:34 tools]$ ls -ltr
total 36
-rwxr-xr-x 1 root root 5996 Jul 10 08:01 generate_volsnapcontent_yaml.sh
-rwxr-xr-x 1 root root 8250 Jul 10 08:01 generate_pv_yaml.sh
-rwxr-xr-x 1 root root 1666 Jul 10 08:01 create_release_tar.sh
drwxr-xr-x 7 root root  328 Jul 10 08:01 ansible
-rwxr-xr-x 1 root root 8953 Jul 10 08:01 spectrum-scale-driver-snap.sh
drwxr-xr-x 3 root root   35 Jul 10 08:01 scripts
drwxr-xr-x 2 root root  119 Jul 10 08:01 olm
drwxr-xr-x 5 root root  113 Jul 10 08:01 ocp-ibm-spectrum-scale-csi-bundle
[root@spectral1 2021_07_10-08:02:04 tools]$
[root@spectral1 2021_07_10-08:02:05 tools]$ ./spectrum-scale-driver-snap.sh -v
ibm-spectrum-scale-csi-driver   Active   35h
IBM Spectrum Scale CSI driver : v2.2.0
Operator Image                : quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator:v2.2.0
Driver Image                  : quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver:v2.2.0
Node Registrar Image          : us.gcr.io/k8s-artifacts-prod/sig-storage/csi-node-driver-registrar:v2.1.0
Attacher Image                : us.gcr.io/k8s-artifacts-prod/sig-storage/csi-attacher:v3.1.0
Provisioner Image             : us.gcr.io/k8s-artifacts-prod/sig-storage/csi-provisioner:v2.1.0
Snapshotter Image             : us.gcr.io/k8s-artifacts-prod/sig-storage/csi-snapshotter:v4.0.0
[root@spectral1 2021_07_10-08:02:16 tools]$
```

- command execution and output 2.
```
[root@spectral1 2021_07_10-08:02:18 tools]$ ./spectrum-scale-driver-snap.sh
ibm-spectrum-scale-csi-driver   Active   35h
Collecting "ibm-spectrum-scale-csi" logs...
The log files will be saved in the folder [./ibm-spectrum-scale-csi-logs_07-10-2021-08:02:25]
kubectl logs --namespace ibm-spectrum-scale-csi-driver StatefulSet/ibm-spectrum-scale-csi-attacher
kubectl logs --namespace ibm-spectrum-scale-csi-driver StatefulSet/ibm-spectrum-scale-csi-provisioner
kubectl logs --namespace ibm-spectrum-scale-csi-driver StatefulSet/ibm-spectrum-scale-csi-snapshotter
kubectl describe CSIScaleOperator --namespace ibm-spectrum-scale-csi-driver
kubectl logs --namespace ibm-spectrum-scale-csi-driver pod/ibm-spectrum-scale-csi-8pbgk
kubectl logs --namespace ibm-spectrum-scale-csi-driver pod/ibm-spectrum-scale-csi-attacher-0
kubectl logs --namespace ibm-spectrum-scale-csi-driver pod/ibm-spectrum-scale-csi-kcfbr
kubectl logs --namespace ibm-spectrum-scale-csi-driver pod/ibm-spectrum-scale-csi-operator-676465b76d-77f2h
kubectl logs --namespace ibm-spectrum-scale-csi-driver pod/ibm-spectrum-scale-csi-provisioner-0
kubectl logs --namespace ibm-spectrum-scale-csi-driver pod/ibm-spectrum-scale-csi-snapshotter-0
kubectl describe all,cm,secret,storageclass,pvc,ds,serviceaccount,clusterroles,clusterrolebindings -l product=ibm-spectrum-scale-csi --namespace ibm-spectrum-scale-csi-driver
kubectl get all,cm,secret,storageclass,pvc,serviceaccount,clusterroles,clusterrolebindings --namespace ibm-spectrum-scale-csi-driver -l product=ibm-spectrum-scale-csi
kubectl get pod --namespace ibm-spectrum-scale-csi-driver -o wide  -l product=ibm-spectrum-scale-csi
kubectl get configmap spectrum-scale-config --namespace ibm-spectrum-scale-csi-driver -o yaml
kubectl get nodes
kubectl describe nodes
kubectl describe ds -l app.kubernetes.io/name=ibm-spectrum-scale-csi-operator -n ibm-spectrum-scale-csi-driver
kubectl cluster-info dump --namespaces kube-system --output-directory=./ibm-spectrum-scale-csi-logs_07-10-2021-08:02:25
Finished collecting "ibm-spectrum-scale-csi" logs in the folder -> ./ibm-spectrum-scale-csi-logs_07-10-2021-08:02:25
[root@spectral1 2021_07_10-08:03:59 tools]$
[root@spectral1 2021_07_10-08:04:17 tools]$ ls -ltr ./ibm-spectrum-scale-csi-logs_07-10-2021-08\:02\:25/
total 6484
-rw-r--r--  1 root root  862701 Jul 10 08:02 ibm-spectrum-scale-csi-attacher.log
-rw-r--r--  1 root root    2104 Jul 10 08:02 ibm-spectrum-scale-csi-attacher
-rw-r--r--  1 root root 1541209 Jul 10 08:02 ibm-spectrum-scale-csi-provisioner.log
-rw-r--r--  1 root root    2110 Jul 10 08:02 ibm-spectrum-scale-csi-provisioner
-rw-r--r--  1 root root  763916 Jul 10 08:02 ibm-spectrum-scale-csi-snapshotter.log
-rw-r--r--  1 root root    2095 Jul 10 08:02 ibm-spectrum-scale-csi-snapshotter
-rw-r--r--  1 root root    2701 Jul 10 08:02 ibm-spectrum-scale-csi-describe-CSIScaleOperator
-rw-r--r--  1 root root   12440 Jul 10 08:02 ibm-spectrum-scale-csi-8pbgk.log
-rw-r--r--  1 root root     129 Jul 10 08:02 ibm-spectrum-scale-csi-8pbgk-previous.log
-rw-r--r--  1 root root  862701 Jul 10 08:02 ibm-spectrum-scale-csi-attacher-0.log
-rw-r--r--  1 root root     149 Jul 10 08:02 ibm-spectrum-scale-csi-attacher-0-previous.log
-rw-r--r--  1 root root   14867 Jul 10 08:02 ibm-spectrum-scale-csi-kcfbr.log
-rw-r--r--  1 root root     129 Jul 10 08:02 ibm-spectrum-scale-csi-kcfbr-previous.log
-rw-r--r--  1 root root   83225 Jul 10 08:02 ibm-spectrum-scale-csi-operator-676465b76d-77f2h.log
-rw-r--r--  1 root root    2736 Jul 10 08:02 ibm-spectrum-scale-csi-operator-676465b76d-77f2h-previous.log
-rw-r--r--  1 root root 1541209 Jul 10 08:02 ibm-spectrum-scale-csi-provisioner-0.log
-rw-r--r--  1 root root     136 Jul 10 08:02 ibm-spectrum-scale-csi-provisioner-0-previous.log
-rw-r--r--  1 root root  763916 Jul 10 08:02 ibm-spectrum-scale-csi-snapshotter-0.log
-rw-r--r--  1 root root     136 Jul 10 08:02 ibm-spectrum-scale-csi-snapshotter-0-previous.log
-rw-r--r--  1 root root   55186 Jul 10 08:02 ibm-spectrum-scale-csi-describe-all-by-label
-rw-r--r--  1 root root    4409 Jul 10 08:02 ibm-spectrum-scale-csi-get-all-by-label
-rw-r--r--  1 root root     888 Jul 10 08:02 ibm-spectrum-scale-csi-configmap
-rw-r--r--  1 root root   15003 Jul 10 08:02 ibm-spectrum-scale-csi-k8snodes
-rw-r--r--  1 root root    4012 Jul 10 08:02 ibm-spectrum-scale-csi-daemonsets
-rw-r--r--  1 root root     624 Jul 10 08:02 ibm-spectrum-scale-csi-versions
-rw-r--r--  1 root root   30236 Jul 10 08:02 nodes.json
drwxr-xr-x 15 root root    4096 Jul 10 08:03 kube-system
[root@spectral1 2021_07_10-08:04:27 tools]$
[root@spectral1 2021_07_10-08:04:28 tools]$ cat ./ibm-spectrum-scale-csi-logs_07-10-2021-08\:02\:25/ibm-spectrum-scale-csi-versions
IBM Spectrum Scale CSI driver : v2.2.0
Operator Image                : quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator:v2.2.0
Driver Image                  : quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver:v2.2.0
Node Registrar Image          : us.gcr.io/k8s-artifacts-prod/sig-storage/csi-node-driver-registrar:v2.1.0
Attacher Image                : us.gcr.io/k8s-artifacts-prod/sig-storage/csi-attacher:v3.1.0
Provisioner Image             : us.gcr.io/k8s-artifacts-prod/sig-storage/csi-provisioner:v2.1.0
Snapshotter Image             : us.gcr.io/k8s-artifacts-prod/sig-storage/csi-snapshotter:v4.0.0
[root@spectral1 2021_07_10-08:04:38 tools]$
[root@spectral1 2021_07_10-08:04:40 tools]$
```

**Comment by deeghuge** [comment]
Output from my openshift cluster
```
 ./spectrum-scale-driver-snap.sh -v
ibm-spectrum-scale-csi-driver                      Active   126d
IBM Spectrum Scale CSI driver : v2.2.0
Operator Image                : quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator:v2.2.0
Driver Image                  : quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver:v2.2.0
Node Registrar Image          : us.gcr.io/k8s-artifacts-prod/sig-storage/csi-node-driver-registrar:v2.1.0
Attacher Image                : us.gcr.io/k8s-artifacts-prod/sig-storage/csi-attacher:v3.1.0
Provisioner Image             : us.gcr.io/k8s-artifacts-prod/sig-storage/csi-provisioner:v2.1.0
Snapshotter Image             : us.gcr.io/k8s-artifacts-prod/sig-storage/csi-snapshotter:v4.0.0
```

**Comment by deeghuge** [comment]
Hi @kulkarnicr, Please help remove following extra output during snap
ibm-spectrum-scale-csi-driver                      Active   126d

**Review by deeghuge — APPROVED** [review]
LGTM

**Review by Jainbrt — CHANGES_REQUESTED** [review]
1. Did we miss the livenessprobe container details in find_versions?

2. Should we explain what is -v stands for in the script help message ?

Suggestion : we can skip to find the attacher, provisioner and snapshotter pod name from the namespace because these name are static ( due to statefulsets)

**Comment by kulkarnicr** [comment]
> 
> 
>     1. Did we miss the livenessprobe container details in find_versions?
> 
>     2. Should we explain what is -v stands for in the script help message ?
> 
> 
> Suggestion : we can skip to find the attacher, provisioner and snapshotter pod name from the namespace because these name are static ( due to statefulsets)


Addressed the suggested changes. Please review.

**Review by Jainbrt — APPROVED** [review]
LGTM

**Pull request merged**
