### PR TITLE
Tolerations for sidecar to schedule on Infra/Master node

### PR DESCRIPTION
**Pull request by hemalathagajendran**
Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature Enhancement
- [ ] Test Automation 
- [ ] Code Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Community Operator listing 
- [ ] Other (please describe): 

## What is the current behavior?
Sidecars are not scheduled on Infra/Master node

## What is the new behavior?
Sidecars will be scheduled on Master/Infra node with corresponding tolerations

## How risky is this change?
- [x] Small, isolated change
- [ ] Medium, requires regression testing
- [ ] Large, requires functional and regression testing

### CODE REVIEW

**Comment by hemalathagajendran** [comment]
Upgrade scenario is tested and it works fine.

**Review by amdabhad — APPROVED** [review]

**Comment by hemalathagajendran** [comment]
Tolerations applied on sidecar:
Tolerations:         CriticalAddonsOnly op=Exists
                             node-role.kubernetes.io/control-plane:NoSchedule op=Exists
                             node-role.kubernetes.io/infra:NoSchedule op=Exists
                             node-role.kubernetes.io/master:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s

**Comment by hemalathagajendran** [comment]
Image to test: quay.io/hemalatha_gajendran/operator_sidecar_tolerations

**Comment by hemalathagajendran** [comment]
Latest Image to test: quay.io/hemalatha_gajendran/operator_sidecar_tolerations_final

**Comment by deeghuge** [comment]
> Tolerations applied on sidecar: (openshift cluster) Tolerations: CriticalAddonsOnly op=Exists node-role.kubernetes.io/control-plane:NoSchedule op=Exists node-role.kubernetes.io/infra:NoSchedule op=Exists node-role.kubernetes.io/master:NoSchedule op=Exists node.kubernetes.io/not-ready:NoExecute op=Exists for 300s node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
> 
> Tolerations: node-role.kubernetes.io/control-plane:NoSchedule op=Exists (kubernetes cluster) node-role.kubernetes.io/infra:NoSchedule op=Exists node-role.kubernetes.io/master:NoSchedule op=Exists node.kubernetes.io/not-ready:NoExecute op=Exists for 300s node.kubernetes.io/unreachable:NoExecute op=Exists for 300s Events:

@hemalathagajendran What is toleration we get on pods when no toleration is in CR for k8s ?

**Comment by saurabhwani5** [comment]
There is one corner case which we found is when workers are in notReady state and we apply toleration in cso  to bring driver pod on master node on k8s cluster and other sidecars too but this doesn't work as operator can be only scheduled on worker node

**Comment by deeghuge** [comment]
> There is one corner case which we found is when workers are in notReady state and we apply toleration in cso to bring driver pod on master node on k8s cluster and other sidecars too but this doesn't work as operator can be only scheduled on worker node

@saurabhwani5 Operator yaml is deployed by customer/user so he can always add toleration to get scheduled on master node. Have you tried this ?

**Comment by hemalathagajendran** [comment]
Latest image to test after merge from dev branch: quay.io/hemalatha_gajendran/operator_sidecar_tolerations_sep13

**Pull request merged**
