### PR TITLE
Add a copy of the default Kustomization to the config dir

### PR DESCRIPTION
**Pull request by tychristensen**
In order to copy the manifests via URL, the directories in the Kustomization (manager, rbac and crd) must either be within the same directory as the Kustomization or in a subdirectory. In this PR I'm adding a copy of the kustomization.yaml to the config directory so that this can be used to pull the CSI manifests via URL.

### CODE REVIEW

**Comment by lostasi** [comment]
@deeghuge @madhuthorat Do we have any outlook on this?

**Comment by Jainbrt** [comment]
@tychristensen could you please rebase and target this to dev branch instead dev-2.4.0. ?

**Review by deeghuge — APPROVED** [review]
lgtm

**Review by madhuthorat — APPROVED** [review]
LGTM

**Pull request merged**
