### PR TITLE
GPFS health check and enable liveness probe

### PR DESCRIPTION
**Pull request by madhuthorat**

### CODE REVIEW

**Review by Jainbrt — APPROVED** [review]
Chetan has tested this under story 275471. LGTM

**Comment by Jainbrt** [comment]
@madhuthorat Could you please elaborate in PR comment section about this problem/resolution for future ref purpose.?

**Comment by kulkarnicr** [comment]
Following tests were executed for liveness probe testing and all of them passed.

1. install liveness probe images - should succeed
2. csi driver pods should show 3 containers - an extra container added for liveness-probe
3. pre-req: GPFS is up on all nodes
liveness probe container log should show success
csi container log should show gpfs healthy
4. pre-req: GPFS down on all nodes
liveness probe container log should show success on all nodes
csi container log should show gpfs unhealthy on all nodes
5. pre-req: GPFS is down on node1 but up on node2
liveness probe container log should show success on node1 and node2
csi container log should show gpfs unhealthy on node1 and healthy on node2
6. pre-req: csi node name (e.g. deism3.fyre.ibm.com) and gpfs node name (deism3) differs; gpfs is down on that node
liveness probe container log should show success
csi container log should show gpfs unhealthy
7. pre-req: csi node name (e.g. deism3.fyre.ibm.com) and gpfs node name (deism3) differs; gpfs is running on that node
liveness probe container log should show success
csi container log should show gpfs healthy
8. Ensure liveness-probe checks health every 30 seconds.
9. Ensure Probe() function runs every 30 seconds and checks GPFS health.

**Comment by madhuthorat** [comment]
Purpose of this PR - One of the requirements for CSI-CNSA integration is to make CSI aware about GPFS. This PR takes care of making CSI pods aware about GPFS health by doing the following:
1. Use REST API "Nodes/{name}/health/states: GET" in CSI driver code to get GPFS health status on a node.
2. Also update Probe() function to call the REST API to get GPFS health status. The Probe() function does the following:
    a) Add a log to indicate GPFS is healthy or unhealthy on the node.
    b) Return with SUCCESS status (irrespective of GPFS status). We don't want CSI driver PODS to restart as of now when GPFS is unhealthy, so we return with SUCCESS status from Probe() status. This is avoid loosing valuable CSI driver logs in case of CSI POD restarts.
3. Add a container to have liveness probe in existing CSI PODs.
4. Set various options, port for liveness probe in operator code. The options for liveness probe are set such that, one minute after CSI driver pod has started, the liveness probe would start sending "Probe" requests to CSI container . It would thereafter continue sending "Probe" requests every 30 seconds to the CSI container. Thus "Probe()" function, would be invoked every 30 seconds and GPFS health status would be checked and reported in CSI driver logs.

**Review by deeghuge — APPROVED** [review]

**Comment by kulkarnicr** [comment]
liveness probe works post upgrade too (CSI 220 to liveness probe images).

original version: 220 

upgraded version/images:
quay.io/madhuthorat/ibm-spectrum-scale-csi-driver-dev:gpfschk_driver
quay.io/madhuthorat/ibm-spectrum-scale-csi-operator-dev:gpfschk_operator

test result:

1. before upgrade, csi driver pods had two containers [driver-registrar ibm-spectrum-scale-csi]

2. post upgrade, container liveness-probe was added to csi driver pods [driver-registrar liveness-probe ibm-spectrum-scale-csi]

3. csi driver pod log for container ibm-spectrum-scale-csi started showing probeRequest and gpfs healthy messages.

I0707 12:09:12.678692       1 utils.go:51] GRPC call: /csi.v1.Identity/Probe
I0707 12:09:12.679079       1 identityserver.go:49] Probe called with args: &csi.ProbeRequest{XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
I0707 12:09:12.679149       1 identityserver.go:62] Probe: scale node mapping not found for K8sNodePrefix_spectral2.fyre.ibm.com using spectral2.fyre.ibm.com
I0707 12:09:12.679170       1 identityserver.go:67] Probe: scalenodeID:spectral2.fyre.ibm.com --known as-- k8snodeName: spectral2.fyre.ibm.com
I0707 12:09:12.791308       1 identityserver.go:81] Probe: GPFS on node spectral2.fyre.ibm.com is healthy

**Pull request merged**
