### PR TITLE
Upgrading Custom Resource Definition to v1

### LINKED ISSUE #256: Need support for v1 API for CRD objects
**Describe the bug**
we need support for v1 API for CRD objects as betav1 CRD will not be available in k8s 1.22 version 

**To Reproduce**
we need support for v1 API for CRD objects as betav1 CRD will not be available in k8s 1.22 version

**Expected behavior**
Need support for v1 API for CRD objects

### PR DESCRIPTION
**Pull request by mew2057**
Fixes #256

Converts the  CRD to v1 from v1beta.  It looks like minikube is having problems, however, because the CRD can't be applied in the travis environment.

### CODE REVIEW

**Comment by mew2057** [comment]
Pushed a fix which should resolve the error.

**Comment by mew2057** [comment]
I'm not sure why but the k8s version  on travis doesn't have the v1 definition for the CRD, as a result the travis build will be inherently broken, until a resolution can be  found.

**Comment by mew2057** [comment]
Can you run: 
`kubectl get csiscaleoperators.csi.ibm.com -A`


There's nothing in the role that should prevent this from working.

**Comment by Jainbrt** [comment]
```
[root@oc-w3 configfile]# kubectl get csiscaleoperators.csi.ibm.com -A
NAMESPACE                       NAME                     AGE
ibm-spectrum-scale-csi-driver   ibm-spectrum-scale-csi   34s
```

**Comment by mew2057** [comment]
So it's present in the listing. As a question is this a fresh install of the operator or an upgrade?

**Comment by Jainbrt** [comment]
It is a fresh install

**Pull request merged**
