### PR TITLE
Remove scaleHostpath and GPFS mount

### PR DESCRIPTION
**Pull request by smitaraut**
RTC 236451
- Removed SCALE_HOSTPATH parameter from CRD
- Removed the volume mount in driver pod for GPFS path

Tested that PVCs can be created and mounted. Also tested the upgrade path.

This had ID impact to delete the documentation around SCALE_HOSTPATH

### CODE REVIEW

**Review by Jainbrt — COMMENTED** [review]
After upgrade from 2.1.0 to this PR build, scalehostpath is still accessible from csi pod because after upgrade operator is not able to update daemonset template

**Comment by smitaraut** [comment]
> After upgrade from 2.1.0 to this PR build, scalehostpath is still accessible from csi pod because after upgrade operator is not able to update daemonset template

We'll have to go ahead with this limitation. The earlier mount cannot be removed on upgrade due to complexity in patch merge for list of volumeMount maps. If existing volume mounts are to be removed then the driver/operator needs to be re-deployed.

**Comment by madhuthorat** [comment]
Will be good to merge this after operator changes for operator sdk 1.3/1.4 are pushed, as the code changes has new line of code like:
+    namespace: "{{meta.namespace}}"

"meta." won't work with Operator SDK v1.3/v1.4. We would need to replace with "ansible_operator_meta."

**Review by madhuthorat — DISMISSED** [review]
Looks good to me.

**Review by Jainbrt — COMMENTED** [review]
@smitaraut with new change for deleting the deamonset, what is expecting behavior. Do we say that this upgrade will be disruptive upgrade until old ds deleted and new one comes up ?

**Comment by smitaraut** [comment]
> @smitaraut with new change for deleting the deamonset, what is expecting behavior. Do we say that this upgrade will be disruptive upgrade until old ds deleted and new one comes up ?

This is probably as disruptive as our previous upgrades as the driver pods are restarted even there. For transparency we can mention that ds is recreated in this upgrade.

**Review by Jainbrt — CHANGES_REQUESTED** [review]
Remove daemonset is getting called in every reconciliation 

```
[root@oc-w3 ibm-spectrum-scale-csi]# grep -rni  "Remove daemonset"  operator.logs
504:TASK [csiscaleoperator : Remove daemonset] *************************************
508:{"level":"info","ts":1614691691.600548,"logger":"logging_event_handler","msg":"[playbook task]","name":"ibm-spectrum-scale-csi","namespace":"ibm-spectrum-scale-csi-driver","gvk":"csi.ibm.com/v1, Kind=CSIScaleOperator","event_type":"playbook_on_task_start","job":"4751997750760398084","EventData.Name":"csiscaleoperator : Remove daemonset"}
1729:TASK [csiscaleoperator : Remove daemonset] *************************************
1733:{"level":"info","ts":1614691866.9012094,"logger":"logging_event_handler","msg":"[playbook task]","name":"ibm-spectrum-scale-csi","namespace":"ibm-spectrum-scale-csi-driver","gvk":"csi.ibm.com/v1, Kind=CSIScaleOperator","event_type":"playbook_on_task_start","job":"4831389563158288344","EventData.Name":"csiscaleoperator : Remove daemonset"}
2751:TASK [csiscaleoperator : Remove daemonset] *************************************
2755:{"level":"info","ts":1614692039.1044915,"logger":"logging_event_handler","msg":"[playbook task]","name":"ibm-spectrum-scale-csi","namespace":"ibm-spectrum-scale-csi-driver","gvk":"csi.ibm.com/v1, Kind=CSIScaleOperator","event_type":"playbook_on_task_start","job":"2338498362660772719","EventData.Name":"csiscaleoperator : Remove daemonset"}
3756:TASK [csiscaleoperator : Remove daemonset] *************************************
3760:{"level":"info","ts":1614692132.6150472,"logger":"logging_event_handler","msg":"[playbook task]","name":"ibm-spectrum-scale-csi","namespace":"ibm-spectrum-scale-csi-driver","gvk":"csi.ibm.com/v1, Kind=CSIScaleOperator","event_type":"playbook_on_task_start","job":"9010467728050264449","EventData.Name":"csiscaleoperator : Remove daemonset"}
4674:TASK [csiscaleoperator : Remove daemonset] *************************************
4678:{"level":"info","ts":1614692209.1182282,"logger":"logging_event_handler","msg":"[playbook task]","name":"ibm-spectrum-scale-csi","namespace":"ibm-spectrum-scale-csi-driver","gvk":"csi.ibm.com/v1, Kind=CSIScaleOperator","event_type":"playbook_on_task_start","job":"6281838661429879825","EventData.Name":"csiscaleoperator : Remove daemonset"}
5592:TASK [csiscaleoperator : Remove daemonset] *************************************

```

**Review by madhuthorat — APPROVED** [review]
Looks good to me.

**Review by deeghuge — APPROVED** [review]

**Review by Jainbrt — APPROVED** [review]
LGTM

**Pull request merged**
