### PR TITLE
Add CG utils for regional DR

### PR DESCRIPTION
**Pull request by amdabhad**
- Add consistency group utils needed for regional DR in CSI repo

### CODE REVIEW

**Review by hemalathagajendran — DISMISSED** [review]

**Review by sam6258 — CHANGES_REQUESTED** [review]
`k8s.io/api v0.27.1`

is way too new for both CSI and CNSA. It corresponds with OCP 4.14. k8s golang dependencies need to straddle our supported release levels.

**Comment by amdabhad** [comment]
> `k8s.io/api v0.27.1`
> 
> is way too new for both CSI and CNSA. It corresponds with OCP 4.14. k8s golang dependencies need to straddle our supported release levels.

Thanks Scott! CSI 2.10 is going to support k8s 1.27 and OCP 4.14 is under cosideration for support in CNSA 5.1.8.0 for 3Q if it GA'es soon.
So for now, moving to the API version v0.26 corresponding to k8s 1.26 which CSI already supports and considering at least OCP 4.13 will be supported by CNSA 5.1.8.0.

**Comment by ste-roth** [comment]
> `k8s.io/api v0.27.1`
> 
> is way too new for both CSI and CNSA. It corresponds with OCP 4.14. k8s golang dependencies need to straddle our supported release levels.

Yes, and in addition a Kubernetes API version update is not required for this change.

**Comment by sam6258** [comment]
Hey @amdabhad I pushed a change to move consistency group to a `pkg` dir. This is more idiomatic for golang than a utils folder. I also removed unused `ctx` variables in the package functions.

**Review by sam6258 — APPROVED** [review]

**Pull request merged**
