### PR TITLE
Cleanup of SecurityContextConstraints

### PR DESCRIPTION
**Pull request by nitishkumar4**
## Pull request checklist

This pull request fixes the following issue:
- https://github.ibm.com/IBMSpectrumScale/scale-core/issues/3177

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature Enhancement
- [ ] Test Automation 
- [ ] Code Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Community Operator listing 
- [ ] Other (please describe): 

## What is the current behavior?

- Removing the `csiScaleOperator` resource from the cluster, was not removing the SCC resource created by the controller.

## What is the new behavior?

- Removing the `csiScaleOperator` resource, invokes finalizer which removes SCC resource.

## How risky is this change?
- [x] Small, isolated change
- [ ] Medium, requires regression testing
- [ ] Large, requires functional and regression testing

### CODE REVIEW

**Comment by nitishkumar4** [comment]
Logs:

```sh
... INFO	csiscaleoperator_controller.deleteSCC	Deleting SecurityContextConstraints resource.	{"Name": "spectrum-scale-csiaccess"}
... INFO	csiscaleoperator_controller.deleteSCC	Deletion of SecurityContextConstraints is successful.	{"Name": "spectrum-scale-csiaccess"}

```

**Review by amdabhad — DISMISSED** [review]
LGTM

**Review by madhuthorat — DISMISSED** [review]
LGTM

**Review by Jainbrt — APPROVED** [review]

**Comment by nitishkumar4** [comment]
Sanity Test done in OCP and k8s cluster.
Private build with SCC changes: quay.io/nitish3356/csi:operator161339

**Review by Jainbrt — APPROVED** [review]

**Review by madhuthorat — APPROVED** [review]
LGTM

**Pull request merged**
