### PR TITLE
Fix for operator  going into error state and cso status as `unknown`. 

### PR DESCRIPTION
**Pull request by nitishkumar4**
## Pull request checklist

This pull request fixes the following issue:
- https://github.com/IBM/ibm-spectrum-scale-csi/issues/720

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature Enhancement
- [ ] Test Automation 
- [ ] Code Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Community Operator listing 
- [ ] Other (please describe): 

## What is the current behavior?

- RCA: package mergo.Merge runs into panic when duplicate values are passed in the CR for spec.Toleraitons and spec.NodeMapping
-  fields. This package is used in following files /opeartor/syncer/csi_node.go and /operator/syncer/csi_syncer.go

- Since the code goes into panic state, reconciliation stops and CSO status is updated to unknown

## What is the new behavior?

- merge.Mergo() method does not go in panic state when duplicate values are passed in CR. 
- For Tolerations: If dupicate values are passed, both the duplicate tolerations are added to pod spec.
- For NodeMapping: If duplicate values are passed, duplicate environment variables with node map information are added to podspec. Inside the pod only one of the duplicate env variables is added.

## How risky is this change?
- [ ] Small, isolated change
- [x] Medium, requires regression testing
- [ ] Large, requires functional and regression testing

### CODE REVIEW

**Comment by nitishkumar4** [comment]
## After

For NodeMapping:
Both duplicate node mapping are added as enviroment variable in podSpec. Since a container cannot have more more then one env variable with same name, only one out of all duplicates is seen inside the pod.

For tolerations:
All the duplicate tolerations are added in podSpec.

**Comment by nitishkumar4** [comment]
Private Build: quay.io/nitish3356/csi:operator-issue

**Comment by nitishkumar4** [comment]
Private build: "quay.io/nitish3356/csi:operator-issuefix"

**Review by Jainbrt — APPROVED** [review]

**Comment by nitishkumar4** [comment]
Private Build: quay.io/nitish3356/csi:operator9622

**Review by amdabhad — APPROVED** [review]

**Comment by monimeht** [comment]
Testing for the PR is completed. 
https://jazz07.rchland.ibm.com:21443/jazz/web/projects/GPFS#action=com.ibm.team.workitem.viewWorkItem&id=299115

**Pull request merged**
