### PR TITLE
OLM changes for 2.1.0

### PR DESCRIPTION
**Pull request by deeghuge**
OLM changes for 2.1.0

### CODE REVIEW

**Review by Jainbrt — COMMENTED** [review]
.../olm-catalog/ibm-spectrum-scale-csi-operator/2.1.0/csiscaleoperators.csi.ibm.com.crd.yaml  file contains CRD verson v1beta1 while we have already moved to v1 (here : https://github.com/IBM/ibm-spectrum-scale-csi/blob/dev/operator/deploy/crds/csiscaleoperators.csi.ibm.com.crd.yaml) to comply with 1.19 k8s, should this crd file also to  be changed to v1?

**Comment by deeghuge** [comment]
> .../olm-catalog/ibm-spectrum-scale-csi-operator/2.1.0/csiscaleoperators.csi.ibm.com.crd.yaml file contains CRD verson v1beta1 while we have already moved to v1 (here : https://github.com/IBM/ibm-spectrum-scale-csi/blob/dev/operator/deploy/crds/csiscaleoperators.csi.ibm.com.crd.yaml) to comply with 1.19 k8s, should this crd file also to be changed to v1?

done

**Review by smitaraut — APPROVED** [review]
LGTM

**Review by Jainbrt — COMMENTED** [review]
As discussed we need to make changes for v1 CRD schema in OLM bundle as well

**Review by Jainbrt — CHANGES_REQUESTED** [review]
After successful upgrade to 2.1.0, operator pod is failing with below error:
```
[root@remote-w2 ansible]# kubectl logs ibm-spectrum-scale-csi-operator-6ff5775d84-wqvsl -n marketplace
{"level":"info","ts":1604302336.1652875,"logger":"cmd","msg":"Go Version: go1.13.15"}
{"level":"info","ts":1604302336.1653428,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1604302336.165351,"logger":"cmd","msg":"Version of ansible-operator: v0.19.4"}
{"level":"info","ts":1604302336.1653686,"logger":"cmd","msg":"Git commit of ansible-operator: 125d0dfcc71fef4f9d7e2a42b1354cb79ffdee03"}
{"level":"info","ts":1604302336.1657019,"logger":"cmd","msg":"Watching single namespace.","Namespace":"marketplace"}
{"level":"error","ts":1604302336.1831367,"logger":"controller-runtime.manager","msg":"Failed to get API Group-Resources","error":"Unauthorized","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/manager/manager.go:258\ngithub.com/operator-framework/operator-sdk/pkg/ansible.Run\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/run.go:124\nmain.main\n\tsrc/github.com/operator-framework/operator-sdk/cmd/ansible-operator/main.go:32\nruntime.main\n\t/home/travis/.gimme/versions/go1.13.15.linux.amd64/src/runtime/proc.go:203"}
{"level":"error","ts":1604302336.1832297,"logger":"cmd","msg":"Failed to create a new manager.","Namespace":"marketplace","error":"Unauthorized","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible.Run\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/run.go:126\nmain.main\n\tsrc/github.com/operator-framework/operator-sdk/cmd/ansible-operator/main.go:32\nruntime.main\n\t/home/travis/.gimme/versions/go1.13.15.linux.amd64/src/runtime/proc.go:203"}
time="2020-11-02T07:32:16Z" level=fatal msg=Unauthorized
```
And OLM gui is showing below error:
```CustomResourceDefinition.apiextensions.k8s.io "csiscaleoperators.csi.ibm.com" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1", Served:true, Storage:true, Deprecated:false, DeprecationWarning:(*string)(nil), Schema:(*apiextensions.CustomResourceValidation)(0xc01ce238d0), Subresources:(*apiextensions.CustomResourceSubresources)(0xc00fe34250), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead), spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1", Served:true, Storage:true, Deprecated:false, DeprecationWarning:(*string)(nil), Schema:(*apiextensions.CustomResourceValidation)(0xc01ce238d0), Subresources:(*apiextensions.CustomResourceSubresources)(0xc00fe34250), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version subresources may not all be set to identical values (top-level subresources should be used instead)]```

**Comment by Jainbrt** [comment]
We should be updating below files as well with new operator-courier version : 
```
[root@remote-w2 ibm-spectrum-scale-csi]# cat tools/ansible/common/requirements-*
sphinx
sphinx_rtd_theme
recommonmark
operator-courier==2.0.1
pyyaml
molecule
jmespath
sphinx
sphinx_rtd_theme
recommonmark
operator-courier==2.0.1
```

**Pull request closed without merging**
