### PR TITLE
csv update

### PR DESCRIPTION
**Pull request by deeghuge**
Changes : 
- New Logo 
 - Updated Description

Test Suggestion - 
1. Check preview on https://operatorhub.io/preview
2. Check Operator listing on Various platform and Arch

### CODE REVIEW

**Review by Jainbrt — CHANGES_REQUESTED** [review]
Path for  [Custom Resource] need to be updated with new cr.yaml file path

**Comment by deeghuge** [comment]
> Path for [Custom Resource] need to be updated with new cr.yaml file path

done

**Review by Jainbrt — APPROVED** [review]
LGTM

**Review by madhuthorat — COMMENTED** [review]
Looks good to me.

**Pull request merged**
