### PR TITLE
Sidecar Container  Image  Change

### PR DESCRIPTION
**Pull request by mew2057**
Resolves  Issue  #17

Sets the sidecar container images:
- Driver registrar: v1.2.0
- CSI Attacher: v1.2.1
- CSI Provisioner: v1.5.0

### CODE REVIEW

**Comment by mew2057** [comment]
I can't create a volume with any version of the containers in my environment:

```
  Warning  FailedAttachVolume  7s (x10 over 4m17s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-e3594312-4395-457e-8365-5fbf2a581178" : rpc error: code = Internal desc = ControllerPublishVolume : SKIP_MOUNT_UNMOUNT == yes and either fs1 or fs1 in not mounted on node jdun-worker2.
```

I checked the troubleshoot and it looks like this is a node mapping  issue? But the node names are the same in kubectl and gpfs. Also all the have the filesystem mounted.


```
[root ~]# mmlsmount all -L
File system fs1 is mounted on 3 nodes:
  172.16.197.95   jdun-worker2
  172.16.196.134  jdun-worker1
  172.16.194.34   jdun-master
[root ~]# kubectl get nodes
NAME           STATUS   ROLES    AGE   VERSION
jdun-master    Ready    master   14d   v1.16.3
jdun-worker1   Ready    <none>   14d   v1.16.3
jdun-worker2   Ready    <none>   14d   v1.16.3
```


Outside of that everything else appears to be  operational and the pvc even gets created in the gpfs directory (this is with  the most  recent code level).

@smitaraut or @deeghuge  any thoughts?
If this works in your  environments please merge.

**Comment by mew2057** [comment]
That was resolved with node mapping.

**Comment by mew2057** [comment]
I'm still not able to deploy using the cr.

**Comment by mew2057** [comment]
I think it's the `csi-node-driver-registrar`

**Comment by mew2057** [comment]
I tried all of the images independently and  none  of them worked. I think the driver needs to be  updated to allow changes.

**Comment by dunnevan** [comment]
CSI Provisioner v1.0.0 -> v1.1.0 deprecated two command line options that we use (without bumping major versions...)

    --connection-timeout
    --provisioner

We'll have to change how the deployment is done by the operator.  

Also, slightly related question (as provisioner name should match driver name now) - why is our drivername a command line variable?  Is there a good reason for this?

**Comment by smitaraut** [comment]
I have opened another PR #108 in 1.1.0 branch. Closing this one.

**Pull request closed without merging**
